<?php
/**
 * DataTableHelpers Trait - Usage Example
 *
 * @package     WP_DataTable
 * @subpackage  Examples
 * @version     0.2.0
 * @author      arisciwek
 *
 * Path: /wp-datatable/examples/DataTableHelpers-Example.php
 *
 * Description: Complete example showing how to use DataTableHelpers trait
 *              with wp-app-core's DataTableModel for composition pattern.
 *
 * Use Case:
 * Your model extends from wp-app-core's DataTableModel (for query power),
 * but you want to use wp-datatable's UI helpers (buttons, badges, etc).
 *
 * Solution:
 * Use DataTableHelpers trait for composition pattern.
 */

namespace YourPlugin\Models;

use WPAppCore\Models\DataTable\DataTableModel;
use WPDataTable\Traits\DataTableHelpers;

/**
 * Example: Division DataTable Model
 *
 * Extends wp-app-core's DataTableModel for query building,
 * Uses wp-datatable's DataTableHelpers for UI generation.
 */
class DivisionDataTableModel extends DataTableModel {

    // ✅ Include the trait
    use DataTableHelpers;

    /**
     * Constructor - Setup table configuration
     */
    public function __construct() {
        parent::__construct();

        global $wpdb;
        $this->table = $wpdb->prefix . 'app_agency_divisions d';
        $this->index_column = 'd.id';

        $this->searchable_columns = [
            'd.code',
            'd.name'
        ];

        $this->base_joins = [
            "LEFT JOIN {$wpdb->prefix}app_agency_jurisdictions j ON d.id = j.division_id",
            "LEFT JOIN {$wpdb->prefix}wi_regencies wr ON j.jurisdiction_regency_id = wr.id"
        ];
    }

    /**
     * Get columns for SELECT clause
     */
    protected function get_columns(): array {
        return [
            'd.code as code',
            'd.name as name',
            'd.status as status',
            "GROUP_CONCAT(DISTINCT wr.name ORDER BY wr.name SEPARATOR ', ') as wilayah_kerja",
            'd.id as id'
        ];
    }

    /**
     * Format row data for DataTable output
     *
     * ✅ Uses trait methods for UI generation
     */
    protected function format_row($row): array {
        // ✅ Method 1: Use format_panel_row_data() for DT_RowId & DT_RowData
        $panel_data = $this->format_panel_row_data($row, 'division', [
            'status' => $row->status ?? 'active'
        ]);

        // ✅ Method 2: Use generate_action_buttons() for buttons
        $actions = $this->generate_action_buttons($row, [
            'entity' => 'division',  // Required! Used for button class
            'edit_capability' => 'edit_all_divisions',
            'delete_capability' => 'delete_division',
            'text_domain' => 'wp-agency',
            'show_view' => false  // Set true for dual-panel view button
        ]);

        // ✅ Method 3: Use format_status_badge() for status
        $status_badge = $this->format_status_badge($row->status ?? '', [
            'text_domain' => 'wp-agency'
        ]);

        // ✅ Combine everything
        return array_merge(
            $panel_data,  // Adds DT_RowId and DT_RowData
            [
                'code' => $this->esc_output($row->code),
                'name' => $this->esc_output($row->name),
                'wilayah_kerja' => $this->esc_output($row->wilayah_kerja),
                'status' => $status_badge,
                'actions' => $actions
            ]
        );
    }

    /**
     * Example: Custom button generation
     *
     * Shows how to add custom buttons alongside standard edit/delete
     */
    protected function format_row_with_custom_buttons($row): array {
        // Custom approve button
        $approve_button = sprintf(
            '<button type="button" class="button button-small wpdt-action-btn"
                    data-action="approve"
                    data-id="%d"
                    data-entity="division"
                    title="%s">
                <span class="dashicons dashicons-yes"></span>
            </button>',
            esc_attr($row->id),
            esc_attr__('Approve', 'wp-agency')
        );

        $actions = $this->generate_action_buttons($row, [
            'entity' => 'division',
            'edit_capability' => 'edit_all_divisions',
            'delete_capability' => 'delete_division',
            'text_domain' => 'wp-agency',
            'custom_buttons' => [$approve_button]  // ✅ Add custom buttons
        ]);

        return [
            'code' => $this->esc_output($row->code),
            'name' => $this->esc_output($row->name),
            'actions' => $actions  // Now includes: View + Edit + Delete + Approve
        ];
    }
}

/**
 * JavaScript Integration Example
 *
 * The buttons generated by generate_action_buttons() automatically work with
 * wp-datatable's action-buttons-handler.js.
 *
 * File: assets/js/division/division-modal-handler.js
 */
/*
jQuery(document).ready(function($) {
    console.log('[DivisionModal] Initializing...');

    // ✅ Listen to wp-datatable events
    // These events are triggered by action-buttons-handler.js

    // Edit button clicked (class: division-edit-btn)
    $(document).on('wpdt:action-edit', function(e, data) {
        if (data.entity === 'division') {
            console.log('[DivisionModal] Edit clicked:', data.id);

            // Open edit modal
            DivisionModal.open(data.id, 'edit');
        }
    });

    // Delete button clicked (class: division-delete-btn)
    $(document).on('wpdt:action-delete', function(e, data) {
        if (data.entity === 'division') {
            console.log('[DivisionModal] Delete clicked:', data.id);

            // Show confirmation
            DivisionModal.confirmDelete(data.id);
        }
    });

    // Custom action button clicked (data-action="approve")
    $(document).on('wpdt:action-custom', function(e, data) {
        if (data.entity === 'division' && data.action === 'approve') {
            console.log('[DivisionModal] Approve clicked:', data.id);

            // Handle approve
            DivisionModal.approve(data.id);
        }
    });
});
*/

/**
 * Column Configuration Example
 *
 * JavaScript DataTable column configuration
 *
 * File: assets/js/agency/agency-datatable.js
 */
/*
getLazyTableColumns(entity) {
    switch(entity) {
        case 'division':
            return [
                { data: 'code', width: '15%' },
                { data: 'name', width: '30%' },
                { data: 'wilayah_kerja', width: '30%' },
                { data: 'status', width: '10%' },
                {
                    data: 'actions',  // ✅ Actions column
                    width: '15%',
                    orderable: false,
                    searchable: false,
                    className: 'text-center'
                }
            ];
    }
}
*/

/**
 * Benefits Summary
 *
 * ✅ NO code duplication - Reuse trait across all models
 * ✅ Convention-based - Auto {entity}-edit-btn class names
 * ✅ Permission-aware - Auto capability checks
 * ✅ Event-driven - Works with action-buttons-handler.js
 * ✅ Consistent UI - Same styling across all datatables
 * ✅ Keep query power - Still extend wp-app-core's DataTableModel
 * ✅ Flexible - Add custom buttons easily
 */

/**
 * Migration Path
 *
 * Before (Manual):
 * ```php
 * private function generate_action_buttons(int $division_id): string {
 *     $buttons = '';
 *     if (current_user_can('edit_all_divisions')) {
 *         $buttons .= sprintf(
 *             '<button type="button" class="button button-small edit-division" data-id="%d">
 *                 <span class="dashicons dashicons-edit"></span>
 *             </button>',
 *             $division_id
 *         );
 *     }
 *     return $buttons ?: '-';
 * }
 * ```
 *
 * After (With Trait):
 * ```php
 * use DataTableHelpers;
 *
 * protected function format_row($row): array {
 *     return [
 *         'actions' => $this->generate_action_buttons($row, [
 *             'entity' => 'division',
 *             'edit_capability' => 'edit_all_divisions',
 *             'delete_capability' => 'delete_division'
 *         ])
 *     ];
 * }
 * ```
 *
 * Result:
 * - 15+ lines of code → 6 lines
 * - Manual permission checks → Auto
 * - Custom class names → Convention-based
 * - No event integration → Auto events
 */

// ============================================================================
// AUTO-WIRE SYSTEM: ZERO JAVASCRIPT NEEDED!
// ============================================================================

/**
 * NEW v2.0: Auto-Wire Action Buttons to WP-Modal
 *
 * Consumer plugins dapat eliminate ALL JavaScript untuk edit/delete operations!
 * Hanya perlu provide configuration, wp-datatable + wp-modal handle sisanya.
 *
 * Requirements:
 * - wp-modal plugin active
 * - wp-datatable v2.0+
 * - Model extends AbstractDataTable (not DataTableModel)
 */

namespace YourPlugin\ModelsV2;

use WPDataTable\Core\AbstractDataTable;

/**
 * Division DataTable Model - Auto-Wire Version
 *
 * Extends AbstractDataTable (bukan DataTableModel).
 * Override get_action_button_config() untuk auto-wire.
 */
class DivisionDataTableModelV2 extends AbstractDataTable {

    public function __construct() {
        parent::__construct();

        global $wpdb;
        $this->table = $wpdb->prefix . 'app_agency_divisions d';
        $this->index_column = 'd.id';
        $this->columns = [
            'd.id as id',
            'd.code as code',
            'd.name as name',
            'd.status as status'
        ];
        $this->searchable_columns = ['d.code', 'd.name'];
    }

    public function get_entity_name(): string {
        return 'division';
    }

    public function get_text_domain(): string {
        return 'wp-agency';
    }

    /**
     * ✅ AUTO-WIRE CONFIG: Override this method
     *
     * Ini adalah KUNCI dari auto-wire system!
     * Configuration ini akan:
     * - Auto-generate buttons dengan permission checks
     * - Auto-wire ke wp-modal untuk edit/delete
     * - Auto-handle AJAX form loading
     * - Auto-handle form submission
     * - Auto-refresh DataTable after operations
     *
     * ZERO JavaScript needed in consumer plugin!
     */
    protected function get_action_button_config(): array {
        return [
            'edit' => [
                'enabled' => true,
                'capability' => 'edit_divisions',                    // Permission check
                'modal_title' => __('Edit Division', 'wp-agency'),   // Modal title
                'ajax_action' => 'get_division_form',                // AJAX action to load form HTML
                'submit_action' => 'update_division',                // AJAX action to submit form
                'modal_size' => 'medium',                            // small|medium|large
                'nonce_action' => 'division_nonce',                  // Nonce action name
            ],
            'delete' => [
                'enabled' => true,
                'capability' => 'delete_divisions',
                'ajax_action' => 'delete_division',                      // AJAX action to delete
                'confirm_message' => __('Are you sure?', 'wp-agency'),
                'confirm_title' => __('Confirm Delete', 'wp-agency'),
                'confirm_label' => __('Delete', 'wp-agency'),
                'nonce_action' => 'division_nonce',
            ]
        ];
    }

    /**
     * Format row - Same as before
     */
    protected function format_row($row): array {
        return array_merge(
            $this->format_panel_row_data($row, 'division'),
            [
                'code' => $this->esc_output($row->code ?? ''),
                'name' => $this->esc_output($row->name ?? ''),
                'status' => $this->format_status_badge($row->status ?? 'inactive', [
                    'text_domain' => 'wp-agency',
                    'active_value' => 'aktif'
                ]),
                'actions' => $this->generate_action_buttons($row, [
                    'entity' => 'division',
                    'edit_capability' => 'edit_divisions',
                    'delete_capability' => 'delete_divisions',
                    'text_domain' => 'wp-agency'
                ])
            ]
        );
    }
}

/**
 * ✅ STEP 2: Localize Config to JavaScript
 *
 * Pass config ke modal-integration.js via wp_localize_script
 */
/*
function enqueue_division_config() {
    $model = new DivisionDataTableModelV2();
    $config = $model->get_config();

    wp_localize_script('wp-agency-admin', 'wpdtConfig', [
        'division' => $config  // Entity name as key
    ]);
}
add_action('admin_enqueue_scripts', 'enqueue_division_config');
*/

/**
 * ✅ STEP 3: Create AJAX Handlers
 *
 * Consumer plugin ONLY needs to provide AJAX handlers.
 * NO JavaScript needed for modal/button interactions!
 */

/**
 * AJAX: Get division form (returns HTML)
 */
/*
function ajax_get_division_form() {
    check_ajax_referer('division_nonce', 'nonce');

    if (!current_user_can('edit_divisions')) {
        wp_send_json_error(['message' => 'Permission denied']);
    }

    $id = isset($_GET['id']) ? intval($_GET['id']) : 0;

    // Get data
    global $wpdb;
    $division = $wpdb->get_row($wpdb->prepare(
        "SELECT * FROM {$wpdb->prefix}app_agency_divisions WHERE id = %d",
        $id
    ));

    // Return form HTML
    ob_start();
    ?>
    <form id="division-edit-form" method="post">
        <input type="hidden" name="id" value="<?php echo esc_attr($division->id); ?>">

        <div class="form-field">
            <label><?php _e('Code', 'wp-agency'); ?></label>
            <input type="text" name="code" value="<?php echo esc_attr($division->code); ?>" required>
        </div>

        <div class="form-field">
            <label><?php _e('Name', 'wp-agency'); ?></label>
            <input type="text" name="name" value="<?php echo esc_attr($division->name); ?>" required>
        </div>
    </form>
    <?php
    echo ob_get_clean();
    wp_die();
}
add_action('wp_ajax_get_division_form', 'ajax_get_division_form');
*/

/**
 * AJAX: Update division (returns JSON)
 */
/*
function ajax_update_division() {
    check_ajax_referer('division_nonce', 'nonce');

    if (!current_user_can('edit_divisions')) {
        wp_send_json_error(['message' => __('Permission denied', 'wp-agency')]);
    }

    $id = isset($_POST['id']) ? intval($_POST['id']) : 0;
    $code = isset($_POST['code']) ? sanitize_text_field($_POST['code']) : '';
    $name = isset($_POST['name']) ? sanitize_text_field($_POST['name']) : '';

    // Update database
    global $wpdb;
    $result = $wpdb->update(
        $wpdb->prefix . 'app_agency_divisions',
        ['code' => $code, 'name' => $name, 'updated_at' => current_time('mysql')],
        ['id' => $id],
        ['%s', '%s', '%s'],
        ['%d']
    );

    if ($result !== false) {
        wp_send_json_success([
            'message' => __('Division updated successfully', 'wp-agency')
        ]);
    } else {
        wp_send_json_error([
            'message' => __('Failed to update division', 'wp-agency')
        ]);
    }
}
add_action('wp_ajax_update_division', 'ajax_update_division');
*/

/**
 * AJAX: Delete division (returns JSON)
 */
/*
function ajax_delete_division() {
    check_ajax_referer('division_nonce', 'nonce');

    if (!current_user_can('delete_divisions')) {
        wp_send_json_error(['message' => __('Permission denied', 'wp-agency')]);
    }

    $id = isset($_POST['id']) ? intval($_POST['id']) : 0;

    global $wpdb;
    $result = $wpdb->delete(
        $wpdb->prefix . 'app_agency_divisions',
        ['id' => $id],
        ['%d']
    );

    if ($result) {
        wp_send_json_success([
            'message' => __('Division deleted successfully', 'wp-agency')
        ]);
    } else {
        wp_send_json_error([
            'message' => __('Failed to delete division', 'wp-agency')
        ]);
    }
}
add_action('wp_ajax_delete_division', 'ajax_delete_division');
*/

/**
 * ✅ THAT'S ALL YOU NEED!
 *
 * Auto-wire system handles:
 * - ✅ Button click events (action-buttons-handler.js)
 * - ✅ Modal opening (modal-integration.js + wp-modal)
 * - ✅ Form loading via AJAX
 * - ✅ Form submission via AJAX
 * - ✅ Delete confirmation
 * - ✅ Success/error notifications
 * - ✅ DataTable refresh after operations
 * - ✅ Permission checks
 *
 * Consumer plugin ONLY provides:
 * 1. Model with get_action_button_config()
 * 2. AJAX handlers (get_form, update, delete)
 * 3. Config localization
 *
 * ZERO JavaScript for modal/button interactions!
 */

/**
 * Optional: Custom Event Handling
 *
 * If needed, consumer plugin can listen to events:
 */
/*
jQuery(document).on('wpdt:entity-updated', function(e, data) {
    if (data.entity === 'division') {
        console.log('Division updated:', data.id);
        // Do something custom
    }
});

jQuery(document).on('wpdt:entity-deleted', function(e, data) {
    if (data.entity === 'division') {
        console.log('Division deleted:', data.id);
        // Do something custom
    }
});
*/
